name: flutter_validators_dart
description: A pure dart package of String validators and sanitizers. Inspired by validator.js.
version: 0.1.0
homepage: https://github.com/divyanshub024/flutter_validator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  test: ^1.16.0